# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w6UfXrF8nt0Dydbju-KZz5ZfLmtJ-lr-
"""

import pandas as pd
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense

from google.colab import drive
drive.mount('/content/drive')
path = "/content/drive/MyDrive/data/vader_emolex_rest.csv"
data = pd.read_csv(path)
data.head()

subset= data.head(20000)

train_text = subset['text'].tolist()
train_labels = subset['stars'].tolist()
tokenizer = Tokenizer(num_words=10000)
tokenizer.fit_on_texts(train_text)
train_sequences = tokenizer.texts_to_sequences(train_text)
train_data = pad_sequences(train_sequences, maxlen=500)

import numpy as np
train_text=np.array(train_text)
train_labels = np.array(train_labels)

model = Sequential()
model.add(Embedding(10000, 128))
model.add(LSTM(128))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(train_data, train_labels, epochs=3)

